#!/usr/bin/env python3
"""
PHASE G-DATA 1B — unit conversion reconstruction, REAL DATA run.

Mirrors the rules already implemented and unit-tested in
services/UnitConversionReconstructionService.php (the canonical rule
spec, proven against 18 inline sample SKUs in the prior run) — this
script re-implements them in Python because the real cross-referencing
here (9 spreadsheets, ~1,300 unique SKUs, fuzzy-matching a legacy catalog
that uses a completely different code scheme) is impractical to do
reliably in raw PHP array code. Every rule below is a DETECTOR, never a
corrector — see G11 in docs/PHASE_G10_ANOMALY_RULES.md.

Inputs (per the user's handoff, extracted from
claude_inventory_real_data_handoff.zip into
migration/workspace/raw/handoff_2026-09-17/, NEVER committed to git):
  input_real/template_master_data_barang_{gudang_besar,cibadak,karangtengah}.xlsx
  input_real/stok_awal_september_{gudang_besar,cibadak,karangtengah}.xlsx
  input_real/In Out SCM 01-15 Sept 2026.xlsx
  input_real/In Out Cibadak 01-15 Sept 2026.xlsx
  input_real/dbinventory.xlsx                      (LEGACY EVIDENCE ONLY)
  review_outputs/*.xlsx                            (supporting evidence only)

Outputs:
  migration/workspace/normalized/unit_conversion_candidates_real.json
  migration/workspace/normalized/unit_conversion_review.xlsx  (regenerated by build_conversion_review_real.py)
  migration/workspace/normalized/warehouse_unit_comparison.csv
  migration/workspace/reports/unit_conversion_summary.md      (regenerated by write_summary_real.py)

NO production posting happens here — this script only reads xlsx files
and writes analysis artifacts.
"""
import json
import re
import unicodedata
from collections import defaultdict

import pandas as pd
from rapidfuzz import fuzz, process

BASE = "/home/user/Inventory/migration/workspace/raw/handoff_2026-09-17/claude_inventory_real_data_handoff"
OUT_DIR = "/home/user/Inventory/migration/workspace/normalized"

RATIO_TOLERANCE = 0.05
SCALE_CONSTANTS = [10.0, 100.0, 1000.0, 10000.0, 100000.0]

# Canonical unit list (Phase G2.1 + Section 8's fuller dimension table).
CANONICAL_UNITS = {
    "GR", "KG", "ML", "LTR", "PCS", "BOX", "KARTON", "KARUNG", "LUSIN", "PACK", "ROLL",
    "PAIL", "JAR", "SET", "SHEET", "METER",
}
UNIT_ALIASES = {
    "gr": "GR", "gram": "GR", "grams": "GR", "g": "GR",
    "kg": "KG", "kilogram": "KG", "kilo": "KG",
    "ml": "ML", "mililiter": "ML", "milliliter": "ML",
    "ltr": "LTR", "liter": "LTR", "litre": "LTR", "l": "LTR", "lt": "LTR",
    "pcs": "PCS", "piece": "PCS", "pieces": "PCS", "pc": "PCS", "buah": "PCS", "biji": "PCS", "unit": "PCS",
    "box": "BOX", "kotak": "BOX", "dus": "BOX",
    "karton": "KARTON", "carton": "KARTON", "ctn": "KARTON",
    "karung": "KARUNG", "sack": "KARUNG", "sak": "KARUNG",
    "lusin": "LUSIN", "dozen": "LUSIN",
    "pack": "PACK", "pak": "PACK", "bungkus": "PACK",
    "roll": "ROLL", "gulung": "ROLL",
    "pail": "PAIL", "pail(s)": "PAIL",
    "jar": "JAR", "toples": "JAR",
    "set": "SET",
    "sheet": "SHEET", "lembar": "SHEET",
    "meter": "METER", "mtr": "METER", "m": "METER",
}


def normalize_unit(raw):
    if raw is None or (isinstance(raw, float) and pd.isna(raw)):
        return None
    key = str(raw).strip().lower()
    if key == "":
        return None
    if key in UNIT_ALIASES:
        return UNIT_ALIASES[key]
    upper = key.upper()
    if upper in CANONICAL_UNITS:
        return upper
    return upper  # unrecognized but preserved verbatim, uppercased, for review


# Canonical PHYSICAL-QUANTITY conversions -- only the two dimensions the
# business explicitly confirmed (Phase G-DATA 1B.1): weight (KG<->GR) and
# volume (LTR<->ML). No other unit pair is auto-converted: a plain PCS,
# PACK, SET, etc. is left as-is, never guessed into a weight/volume figure.
CANONICAL_DIMENSION = {
    "KG": ("WEIGHT", 1000.0, "GR"),
    "GR": ("WEIGHT", 1.0, "GR"),
    "LTR": ("VOLUME", 1000.0, "ML"),
    "ML": ("VOLUME", 1.0, "ML"),
}


def normalize_physical_qty(qty, unit):
    """Converts (qty, unit) to a canonical reference unit within its physical
    dimension (GR for weight, ML for volume) so quantities expressed in
    different-but-convertible units can be compared on their real magnitude,
    not their raw numeric value. Returns (normalized_qty, normalized_unit,
    normalization_status). Units outside the two known dimensions are
    returned unchanged (status SAME_UNIT/UNKNOWN_UNIT) -- never guessed."""
    if qty is None or unit is None:
        return qty, unit, "UNKNOWN_UNIT"
    if unit in CANONICAL_DIMENSION:
        _, factor_to_ref, ref_unit = CANONICAL_DIMENSION[unit]
        status = "SAME_UNIT" if unit == ref_unit else "CONVERTED"
        return round(qty * factor_to_ref, 6), ref_unit, status
    return qty, unit, "SAME_UNIT"


def normalize_code(x):
    if x is None or (pd.api.types.is_scalar(x) and pd.isna(x)):
        return None
    if isinstance(x, float):
        return str(int(x)) if x.is_integer() else str(x)
    s = str(x).strip()
    if s.endswith(".0"):
        try:
            return str(int(float(s)))
        except ValueError:
            pass
    return s if s != "" else None


def normalize_name(name):
    if name is None or (isinstance(name, float) and pd.isna(name)):
        return ""
    s = unicodedata.normalize("NFKD", str(name))
    s = re.sub(r"[^A-Za-z0-9]+", " ", s).strip().upper()
    s = re.sub(r"\s+", " ", s)
    return s


NAME_HEURISTIC_MULTI = re.compile(r"@\s*(\d+(?:[.,]\d+)?)\s*[xX]\s*(\d+(?:[.,]\d+)?)\s*([A-Za-z]+)")
NAME_HEURISTIC_SINGLE = re.compile(r"@\s*(\d+(?:[.,]\d+)?)\s*([A-Za-z]+)")


def extract_name_heuristic(item_name):
    if not item_name:
        return None
    m = NAME_HEURISTIC_MULTI.search(item_name)
    if m:
        count = float(m.group(1).replace(",", "."))
        size = float(m.group(2).replace(",", "."))
        return {
            "raw": m.group(0), "total_qty": round(count * size, 6),
            "unit": normalize_unit(m.group(3)), "ambiguous_structure": True,
        }
    m = NAME_HEURISTIC_SINGLE.search(item_name)
    if m:
        return {
            "raw": m.group(0), "total_qty": float(m.group(1).replace(",", ".")),
            "unit": normalize_unit(m.group(2)), "ambiguous_structure": False,
        }
    return None


def price_ratio_candidates(records):
    """records: list of {source, unit, price} for ONE sku. Returns (price_ratio_evidence, unit_label_mismatch_evidence)."""
    best_price_evidence = None
    mismatch_evidence = None
    for i in range(len(records)):
        for j in range(i + 1, len(records)):
            a, b = records[i], records[j]
            if not a["price"] or not b["price"] or a["price"] <= 0 or b["price"] <= 0:
                continue
            ratio = a["price"] / b["price"]
            if ratio < 1:
                continue
            same_unit = a["unit"] and b["unit"] and a["unit"] == b["unit"]
            if same_unit:
                for scale in SCALE_CONSTANTS:
                    if abs(ratio - scale) / scale <= RATIO_TOLERANCE:
                        mismatch_evidence = {
                            "ratio": round(ratio, 2), "suspected_scale": scale,
                            "price_a": a["price"], "unit_a": a["unit"], "source_a": a["source"],
                            "price_b": b["price"], "unit_b": b["unit"], "source_b": b["source"],
                        }
                continue
            nearest = round(ratio)
            if 2 <= nearest <= 200 and abs(ratio - nearest) / nearest <= RATIO_TOLERANCE:
                candidate = {
                    "ratio": round(ratio, 4), "candidate_factor": int(nearest),
                    "price_a": a["price"], "unit_a": a["unit"], "source_a": a["source"],
                    "price_b": b["price"], "unit_b": b["unit"], "source_b": b["source"],
                }
                if best_price_evidence is None:
                    best_price_evidence = candidate
    return best_price_evidence, mismatch_evidence


print("Loading real input files...")

gb_master = pd.read_excel(f"{BASE}/input_real/template_master_data_barang_gudang_besar.xlsx", sheet_name="Master Data Barang")
cb_master = pd.read_excel(f"{BASE}/input_real/template_master_data_barang_cibadak.xlsx", sheet_name="Master Data Barang")
kt_master = pd.read_excel(f"{BASE}/input_real/template_master_data_barang_karangtengah.xlsx", sheet_name="Master Data Barang")

gb_stock = pd.read_excel(f"{BASE}/input_real/stok_awal_september_gudang_besar.xlsx", sheet_name="Stok Awal")
cb_stock = pd.read_excel(f"{BASE}/input_real/stok_awal_september_cibadak.xlsx", sheet_name="Stok Awal")
kt_stock = pd.read_excel(f"{BASE}/input_real/stok_awal_september_karangtengah.xlsx", sheet_name="Stok Awal")

inout_scm = pd.read_excel(f"{BASE}/input_real/In Out SCM 01-15 Sept 2026.xlsx", sheet_name="Detail Per Barang", header=2)
inout_cb = pd.read_excel(f"{BASE}/input_real/In Out Cibadak 01-15 Sept 2026.xlsx", sheet_name="Cibadak", header=2)

dbinv_master = pd.read_excel(f"{BASE}/input_real/dbinventory.xlsx", sheet_name="Master Barang")

scm_recon = pd.read_excel(f"{BASE}/review_outputs/scm_reconciliation_01_15_sep_2026.xlsx", sheet_name="SCM_Reconciliation")
cb_recon = pd.read_excel(f"{BASE}/review_outputs/cibadak_reconciliation_01_15_sep_2026.xlsx", sheet_name="Reconciliation")

for df in (gb_master, cb_master, kt_master, gb_stock, cb_stock, kt_stock):
    df["Kode Barang"] = df["Kode Barang"].apply(normalize_code)
inout_scm["Kode"] = inout_scm["Kode"].apply(normalize_code)
inout_cb["Kode Barang"] = inout_cb["Kode Barang"].apply(normalize_code)
scm_recon["SKU"] = scm_recon["SKU"].apply(normalize_code)
cb_recon["SKU"] = cb_recon["SKU"].apply(normalize_code)

# ---------------------------------------------------------------------
# Build per-warehouse lookup dicts keyed by normalized SKU code
# ---------------------------------------------------------------------
def to_lookup(df, code_col="Kode Barang"):
    out = {}
    for _, row in df.iterrows():
        code = row[code_col]
        if code is None or not isinstance(code, str):
            continue
        out.setdefault(code, []).append(row)
    return out

gb_lookup = to_lookup(gb_master)
cb_lookup = to_lookup(cb_master)
kt_lookup = to_lookup(kt_master)
gb_stock_lookup = to_lookup(gb_stock)
cb_stock_lookup = to_lookup(cb_stock)
kt_stock_lookup = to_lookup(kt_stock)
inout_scm_lookup = to_lookup(inout_scm, "Kode")
inout_cb_lookup = to_lookup(inout_cb, "Kode Barang")
scm_recon_lookup = to_lookup(scm_recon, "SKU")
cb_recon_lookup = to_lookup(cb_recon, "SKU")

# ---------------------------------------------------------------------
# Global SKU universe = union of GB/CB/KT master codes + any opening-only codes (e.g. 33515)
# ---------------------------------------------------------------------
gb_codes = set(gb_lookup)
cb_codes = set(cb_lookup)
kt_codes = set(kt_lookup)
opening_only_codes = (set(gb_stock_lookup) | set(cb_stock_lookup) | set(kt_stock_lookup)) - (gb_codes | cb_codes | kt_codes)
universe = sorted((c for c in (gb_codes | cb_codes | kt_codes | opening_only_codes) if isinstance(c, str)))
print(f"Global SKU universe: {len(universe)} (GB={len(gb_codes)} CB={len(cb_codes)} KT={len(kt_codes)} opening-only={len(opening_only_codes)})")

# ---------------------------------------------------------------------
# KT internal duplicate-row detection (same code, >1 row in KT master)
# ---------------------------------------------------------------------
kt_dup_codes = {code for code, rows in kt_lookup.items() if len(rows) > 1}
print(f"KT master internal duplicate codes: {sorted(kt_dup_codes)}")

# ---------------------------------------------------------------------
# Legacy (dbinventory) name index for fuzzy matching
# ---------------------------------------------------------------------
dbinv_master["_norm_name"] = dbinv_master["Nama Bahan"].apply(normalize_name)
legacy_name_index = defaultdict(list)
for _, row in dbinv_master.iterrows():
    legacy_name_index[row["_norm_name"]].append(row)
legacy_names_list = list(legacy_name_index.keys())

# ---------------------------------------------------------------------
# Reconciliation review flags
# ---------------------------------------------------------------------
recon_flags = {}
for code, rows in scm_recon_lookup.items():
    for row in rows:
        if str(row.get("Issue Code", "")) not in ("", "nan", "None"):
            recon_flags.setdefault(code, []).append({
                "source": "SCM_RECONCILIATION", "issue_code": row["Issue Code"],
                "detail": f"Theoretical ending qty {row.get('Theoretical Ending Qty')} {row.get('Unit')}, status {row.get('Status')}",
            })
for code, rows in cb_recon_lookup.items():
    for row in rows:
        if str(row.get("Status", "")) == "NEGATIVE":
            recon_flags.setdefault(code, []).append({
                "source": "CIBADAK_RECONCILIATION", "issue_code": "NEGATIVE_CLOSING_THEORETICAL",
                "detail": f"Closing Qty Teoritis {row.get('Closing Qty Teoritis')} {row.get('Unit')} — {row.get('Review Note')}",
            })

print(f"Reconciliation review flags found for {len(recon_flags)} SKU(s)")

# ---------------------------------------------------------------------
# Build per-SKU candidate records
# ---------------------------------------------------------------------
results = []
for code in universe:
    gb_row = gb_lookup.get(code, [None])[0]
    cb_row = cb_lookup.get(code, [None])[0]
    kt_rows = kt_lookup.get(code, [])
    kt_row = kt_rows[0] if kt_rows else None

    names = {}
    units = {}
    prices = {}
    categories = {}
    statuses = {}
    if gb_row is not None:
        names["GUDANG_BESAR"] = str(gb_row["Nama Barang"])
        units["GUDANG_BESAR"] = normalize_unit(gb_row["Satuan Dasar"])
        prices["GUDANG_BESAR"] = float(gb_row["Harga per Satuan (Rp)"]) if pd.notna(gb_row["Harga per Satuan (Rp)"]) else None
        categories["GUDANG_BESAR"] = gb_row.get("Kategori") if pd.notna(gb_row.get("Kategori")) else None
        statuses["GUDANG_BESAR"] = gb_row.get("Status") if pd.notna(gb_row.get("Status")) else None
    if cb_row is not None:
        names["CIBADAK"] = str(cb_row["Nama Barang"])
        units["CIBADAK"] = normalize_unit(cb_row["Satuan Dasar"])
        prices["CIBADAK"] = float(cb_row["Harga per Satuan (Rp)"]) if pd.notna(cb_row["Harga per Satuan (Rp)"]) else None
        categories["CIBADAK"] = cb_row.get("Kategori") if pd.notna(cb_row.get("Kategori")) else None
        statuses["CIBADAK"] = cb_row.get("Status") if pd.notna(cb_row.get("Status")) else None
    if kt_row is not None:
        names["KARANG_TENGAH"] = str(kt_row["Nama Barang"])
        units["KARANG_TENGAH"] = normalize_unit(kt_row["Satuan Dasar"])
        prices["KARANG_TENGAH"] = float(kt_row["Harga per Satuan (Rp)"]) if pd.notna(kt_row["Harga per Satuan (Rp)"]) else None
        categories["KARANG_TENGAH"] = kt_row.get("Kategori") if pd.notna(kt_row.get("Kategori")) else None
        statuses["KARANG_TENGAH"] = kt_row.get("Status") if pd.notna(kt_row.get("Status")) else None

    if not names and code in opening_only_codes:
        # Stock-only, no master anywhere (e.g. 33515) — pull identity from whichever stock file has it.
        for wh, lookup in [("GUDANG_BESAR", gb_stock_lookup), ("CIBADAK", cb_stock_lookup), ("KARANG_TENGAH", kt_stock_lookup)]:
            rows = lookup.get(code)
            if rows:
                names[wh] = str(rows[0]["Nama Barang (referensi)"])
                units[wh] = normalize_unit(rows[0]["Satuan Dasar (referensi)"])

    item_name_gb_authority = names.get("GUDANG_BESAR")
    item_name = item_name_gb_authority or next(iter(names.values()), None)

    issues = []
    correction_notes = []

    # ---- Identity: Gudang Besar / SCM is the authoritative Global Master
    # identity (owner decision, Phase G-DATA 1B.1 item 5). When GB has a
    # row, GB's Name/Category/Base Unit/Status win outright and any
    # differing warehouse names become aliases kept for audit only -- this
    # is no longer a BLOCKING conflict. BLOCKED is reserved for the case
    # where no GB row exists to arbitrate between disagreeing transit
    # warehouses (no authoritative source available).
    norm_names = {wh: normalize_name(n) for wh, n in names.items()}
    unique_norms = set(norm_names.values())
    identity_conflict = None
    identity_aliases = {}
    if len(unique_norms) > 1:
        if item_name_gb_authority is not None:
            gb_norm = norm_names["GUDANG_BESAR"]
            identity_aliases = {wh: n for wh, n in names.items() if wh != "GUDANG_BESAR" and norm_names[wh] != gb_norm}
            issues.append("IDENTITY_RESOLVED_VIA_GB_AUTHORITY")
            correction_notes.append(
                "Identity resolved: Gudang Besar name/category/base unit/status is authoritative. "
                "Differing transit names kept as aliases: " +
                "; ".join(f"{wh}=\"{n}\"" for wh, n in identity_aliases.items())
            )
        else:
            identity_conflict = dict(names)
            issues.append("IDENTITY_CONFLICT")

    # ---- Category / Status candidate: GB-authoritative when GB present,
    # else first available transit warehouse. Missing category is left
    # explicitly NULL/NEEDS_CATEGORY -- never invented.
    if item_name_gb_authority is not None:
        category_candidate = categories.get("GUDANG_BESAR")
        status_candidate = statuses.get("GUDANG_BESAR")
    else:
        category_candidate = next((categories[wh] for wh in ("CIBADAK", "KARANG_TENGAH") if categories.get(wh)), None)
        status_candidate = next((statuses[wh] for wh in ("CIBADAK", "KARANG_TENGAH") if statuses.get(wh)), None)

    # ---- Base unit consistency ----
    unique_units = set(u for u in units.values() if u)
    if len(unique_units) > 1:
        issues.append("BASE_UNIT_REVIEW_REQUIRED")

    # ---- Global Master gap ----
    is_global_master_candidate = code not in gb_codes and (code in cb_codes or code in kt_codes or code in opening_only_codes)
    has_live_opening = any(
        code in lookup and float(lookup[code][0].get("Jumlah Stok Awal", 0) or 0) > 0
        for lookup in (gb_stock_lookup, cb_stock_lookup, kt_stock_lookup)
    )
    if is_global_master_candidate:
        if code in opening_only_codes or has_live_opening:
            issues.append("GLOBAL_MASTER_CANDIDATE")
            if not category_candidate:
                issues.append("NEEDS_CATEGORY")
        else:
            issues.append("KT_LOCAL_ONLY_INACTIVE")

    # ---- Duplicate source row (KT internal) ----
    if code in kt_dup_codes:
        issues.append("DUPLICATE_SOURCE_ROW")
        dup_names = [str(r["Nama Barang"]) for r in kt_lookup[code]]
        correction_notes.append(f"Kode {code} muncul {len(kt_lookup[code])}x di master Karang Tengah dengan variasi nama: {dup_names}. Gunakan SATU identitas global, jangan buat item duplikat.")

    # ---- Name heuristic ----
    name_evidence = extract_name_heuristic(item_name) if item_name else None
    if name_evidence:
        issues.append("NAME_DERIVED_CANDIDATE")
        if name_evidence["ambiguous_structure"]:
            issues.append("PACKAGE_STRUCTURE_UNCLEAR")
        norm_qty, norm_unit, norm_status = normalize_physical_qty(name_evidence["total_qty"], name_evidence["unit"])
        name_evidence["raw_qty"] = name_evidence["total_qty"]
        name_evidence["raw_unit"] = name_evidence["unit"]
        name_evidence["normalized_qty"] = norm_qty
        name_evidence["normalized_unit"] = norm_unit
        name_evidence["normalization_status"] = norm_status

    # ---- Transaction evidence ----
    txn_evidence = {}
    if code in inout_scm_lookup:
        r = inout_scm_lookup[code][0]
        txn_evidence["GUDANG_BESAR"] = {
            "unit": normalize_unit(r["Satuan"]), "price": float(r["Harga"]) if pd.notna(r["Harga"]) else None,
            "qty_in": float(r["Qty Penerimaan"]) if pd.notna(r["Qty Penerimaan"]) else 0,
            "qty_out": float(r["Qty Total Pengambilan"]) if pd.notna(r["Qty Total Pengambilan"]) else 0,
        }
    if code in inout_cb_lookup:
        r = inout_cb_lookup[code][0]
        txn_evidence["CIBADAK"] = {
            "unit": normalize_unit(r["Satuan"]), "price": float(r["Harga"]) if pd.notna(r["Harga"]) else None,
            "qty_in": float(r["Total Penerimaan"]) if pd.notna(r["Total Penerimaan"]) else 0,
            "qty_out": float(r["Total Pengeluaran"]) if pd.notna(r["Total Pengeluaran"]) else 0,
        }
    txn_consistent = True
    for wh, ev in txn_evidence.items():
        if wh in units and ev["unit"] and units[wh] and ev["unit"] != units[wh]:
            txn_consistent = False
            issues.append("TRANSACTION_UNIT_MISMATCH")

    # ---- Legacy evidence (fuzzy name match against dbinventory) ----
    legacy_row = None
    legacy_match_score = None
    if item_name:
        nname = normalize_name(item_name)
        if nname in legacy_name_index:
            legacy_row = legacy_name_index[nname][0]
            legacy_match_score = 100.0
        else:
            match = process.extractOne(nname, legacy_names_list, scorer=fuzz.token_sort_ratio)
            if match and match[1] >= 90:
                legacy_row = legacy_name_index[match[0]][0]
                legacy_match_score = match[1]
    legacy_evidence = None
    if legacy_row is not None:
        legacy_evidence = {
            "legacy_source": "dbinventory.xlsx :: Master Barang",
            "match_score": legacy_match_score,
            "legacy_kode_bahan": legacy_row.get("Kode Bahan"),
            "legacy_kemasan_beli": legacy_row.get("Kemasan Beli"),
            "legacy_isi_kemasan": legacy_row.get("Isi Kemasan"),
            "legacy_satuan_kemasan": legacy_row.get("Satuan Kemasan"),
            "legacy_isi_dasar": legacy_row.get("Isi Dasar"),
            "legacy_satuan_dasar_hpp": legacy_row.get("Satuan Dasar HPP"),
        }
        issues.append("LEGACY_CONVERSION_CANDIDATE")
        _legacy_isi_dasar = legacy_evidence.get("legacy_isi_dasar")
        _legacy_unit_raw = normalize_unit(legacy_evidence.get("legacy_satuan_dasar_hpp"))
        if _legacy_isi_dasar not in (None, "") and pd.notna(_legacy_isi_dasar):
            try:
                _lqty = float(_legacy_isi_dasar)
                _lnorm_qty, _lnorm_unit, _lnorm_status = normalize_physical_qty(_lqty, _legacy_unit_raw)
            except (TypeError, ValueError):
                _lqty, _lnorm_qty, _lnorm_unit, _lnorm_status = None, None, None, "UNKNOWN_UNIT"
            legacy_evidence["legacy_isi_dasar_raw_qty"] = _lqty
            legacy_evidence["legacy_isi_dasar_raw_unit"] = _legacy_unit_raw
            legacy_evidence["legacy_isi_dasar_normalized_qty"] = _lnorm_qty
            legacy_evidence["legacy_isi_dasar_normalized_unit"] = _lnorm_unit
            legacy_evidence["legacy_isi_dasar_normalization_status"] = _lnorm_status

    # ---- Price ratio (across GB/CB/KT master prices) ----
    price_records = [{"source": f"MASTER_{wh}", "unit": units.get(wh), "price": p} for wh, p in prices.items() if p]
    for wh, lookup in [("GUDANG_BESAR", gb_stock_lookup), ("CIBADAK", cb_stock_lookup), ("KARANG_TENGAH", kt_stock_lookup)]:
        rows = lookup.get(code)
        if rows:
            op_price = rows[0].get("Harga per Satuan (Rp)")
            op_unit = normalize_unit(rows[0].get("Satuan Dasar (referensi)"))
            if pd.notna(op_price) and float(op_price) > 0:
                price_records.append({"source": f"OPENING_{wh}", "unit": op_unit, "price": float(op_price)})
    for wh, ev in txn_evidence.items():
        if ev.get("price"):
            price_records.append({"source": f"TRANSACTION_{wh}", "unit": ev.get("unit"), "price": ev["price"]})
    price_evidence, mismatch_evidence = price_ratio_candidates(price_records) if len(price_records) >= 2 else (None, None)
    if mismatch_evidence:
        issues.append("UNIT_LABEL_MISMATCH")
    elif price_evidence:
        issues.append("PRICE_RATIO_SUPPORTS_CONVERSION")
        # candidate_factor means "1 unit_a = candidate_factor * unit_b" -- the
        # physical unit the factor is denominated in is unit_b.
        _pnorm_qty, _pnorm_unit, _pnorm_status = normalize_physical_qty(
            float(price_evidence["candidate_factor"]), price_evidence.get("unit_b")
        )
        price_evidence["raw_qty"] = price_evidence["candidate_factor"]
        price_evidence["raw_unit"] = price_evidence.get("unit_b")
        price_evidence["normalized_qty"] = _pnorm_qty
        price_evidence["normalized_unit"] = _pnorm_unit
        price_evidence["normalization_status"] = _pnorm_status

    # ---- Movement reconciliation review ----
    if code in recon_flags:
        issues.append("MOVEMENT_RECONCILIATION_REVIEW")

    # ---- Evidence agreement -> confidence ----
    # Only REAL candidate packaging-factor values count here (name heuristic,
    # price ratio, legacy isi_dasar). Plain "transaction unit matches master
    # unit" is NOT counted as independent evidence of a packaging factor —
    # that would be true for almost every base-unit-only item and would
    # inflate confidence for SKUs that simply need no conversion at all.
    # Transaction evidence is still surfaced (scm/cibadak_transaction_evidence
    # columns) for a human to weigh, just not folded into this score.
    #
    # CRITICAL (Phase G-DATA 1B.1 fix): before comparing two candidate
    # values, each is normalized to a common physical unit first (KG<->GR,
    # LTR<->ML). Comparing RAW numeric values regardless of unit (the old
    # behaviour) produced false conflicts whenever name evidence and legacy
    # evidence agreed on the same real quantity but expressed it in
    # different units (e.g. name "@1KG" vs legacy isi_dasar=1000 Gr are the
    # SAME 1000 g, not a conflict). Two values can only be clustered
    # together when their NORMALIZED units match.
    candidate_factors = []
    if name_evidence and not name_evidence["ambiguous_structure"]:
        candidate_factors.append({
            "source": "NAME_HEURISTIC",
            "raw_qty": name_evidence["raw_qty"], "raw_unit": name_evidence["raw_unit"],
            "normalized_qty": name_evidence["normalized_qty"], "normalized_unit": name_evidence["normalized_unit"],
        })
    if price_evidence and "normalized_qty" in price_evidence:
        candidate_factors.append({
            "source": "PRICE_RATIO",
            "raw_qty": price_evidence["raw_qty"], "raw_unit": price_evidence["raw_unit"],
            "normalized_qty": price_evidence["normalized_qty"], "normalized_unit": price_evidence["normalized_unit"],
        })
    if legacy_evidence and legacy_evidence.get("legacy_isi_dasar_normalized_qty") not in (None, ""):
        candidate_factors.append({
            "source": "LEGACY",
            "raw_qty": legacy_evidence["legacy_isi_dasar_raw_qty"], "raw_unit": legacy_evidence["legacy_isi_dasar_raw_unit"],
            "normalized_qty": legacy_evidence["legacy_isi_dasar_normalized_qty"], "normalized_unit": legacy_evidence["legacy_isi_dasar_normalized_unit"],
        })

    evidence_count = 0
    normalization_trace = []
    if candidate_factors:
        # Cluster entries that mutually agree in NORMALIZED unit AND
        # magnitude (within tolerance); evidence_count is the size of the
        # LARGEST agreeing cluster. More than one distinct cluster (values
        # that don't fit together even after unit normalization) => genuine
        # conversion conflict.
        clusters = []  # each cluster: list of candidate_factor dicts
        for cf in candidate_factors:
            placed = False
            v, u = cf["normalized_qty"], cf["normalized_unit"]
            for cluster in clusters:
                ref = cluster[0]
                same_unit = (u is not None and ref["normalized_unit"] is not None and u == ref["normalized_unit"])
                if same_unit and ref["normalized_qty"] not in (None, 0) and abs(v - ref["normalized_qty"]) / abs(ref["normalized_qty"]) <= RATIO_TOLERANCE:
                    cluster.append(cf)
                    placed = True
                    break
            if not placed:
                clusters.append([cf])
        clusters.sort(key=len, reverse=True)
        evidence_count = len(clusters[0])
        verdict = "AGREEMENT" if len(clusters) == 1 else "CONFLICT"
        if len(clusters) > 1:
            issues.append("CONVERSION_CONFLICT")
        for cf in candidate_factors:
            normalization_trace.append({
                "source": cf["source"], "raw_qty": cf["raw_qty"], "raw_unit": cf["raw_unit"],
                "normalized_qty": cf["normalized_qty"], "normalized_unit": cf["normalized_unit"],
                "result": verdict,
            })

    if identity_conflict is not None:
        confidence = None
        review_status = "BLOCKED"
    elif evidence_count >= 3:
        confidence = "HIGH"
        review_status = "PENDING"
    elif evidence_count == 2:
        confidence = "MEDIUM"
        review_status = "PENDING"
    elif evidence_count == 1:
        confidence = "LOW"
        review_status = "PENDING"
    else:
        confidence = None
        review_status = "PENDING"
        if not issues:
            issues.append("NO_EVIDENCE_FOUND")

    issue_detail_parts = []
    if identity_conflict:
        issue_detail_parts.append("Identity conflict: " + " vs ".join(f"{wh}=\"{n}\"" for wh, n in identity_conflict.items()) + " — BLOCKED until SKU identity is resolved (no Gudang Besar row present to arbitrate).")
    if identity_aliases:
        issue_detail_parts.append(
            "Identity resolved via Gudang Besar authority (owner decision). Aliases retained for audit: " +
            "; ".join(f"{wh}=\"{n}\"" for wh, n in identity_aliases.items())
        )
    if normalization_trace:
        trace_str = "; ".join(
            f"{t['source']}: raw={t['raw_qty']}{t['raw_unit']} -> normalized={t['normalized_qty']}{t['normalized_unit']} ({t['result']})"
            for t in normalization_trace
        )
        issue_detail_parts.append(f"Normalization trace: {trace_str}.")
    if mismatch_evidence:
        issue_detail_parts.append(f"Price ratio {mismatch_evidence['ratio']}x on same unit ({mismatch_evidence['unit_a']}) between {mismatch_evidence['source_a']} and {mismatch_evidence['source_b']} is close to a {mismatch_evidence['suspected_scale']}x scale constant — possible mislabeled unit, not a real conversion. Do not auto-correct.")
    if "GLOBAL_MASTER_CANDIDATE" in issues:
        issue_detail_parts.append("Stock-only or transit-local item not yet in the Global (Gudang Besar) master — proposed as a Global Master candidate using available identity/unit; category left blank if unavailable.")
    if "KT_LOCAL_ONLY_INACTIVE" in issues:
        issue_detail_parts.append("Exists only in Karang Tengah's local master, not in Global master; currently Non-Aktif or zero live opening stock — lower priority, informational.")
    if code in recon_flags:
        for f in recon_flags[code]:
            issue_detail_parts.append(f"[{f['source']}] {f['issue_code']}: {f['detail']}")
    for cn in correction_notes:
        issue_detail_parts.append(cn)

    results.append({
        "sku": code,
        "item_name": item_name,
        "identity_aliases": identity_aliases or None,
        "category_candidate": category_candidate,
        "status_candidate": status_candidate,
        "gudang_besar_unit": units.get("GUDANG_BESAR"),
        "cibadak_unit": units.get("CIBADAK"),
        "karangtengah_unit": units.get("KARANG_TENGAH"),
        "legacy_base_unit": legacy_evidence.get("legacy_satuan_dasar_hpp") if legacy_evidence else None,
        "global_base_unit_candidate": next(iter(unique_units)) if len(unique_units) == 1 else None,
        "normalization_trace": normalization_trace or None,
        "legacy_middle_unit": legacy_evidence.get("legacy_satuan_kemasan") if legacy_evidence else None,
        "legacy_middle_conversion": legacy_evidence.get("legacy_isi_kemasan") if legacy_evidence else None,
        "middle_unit_candidate": None,
        "middle_conversion_candidate": None,
        "legacy_purchase_unit": legacy_evidence.get("legacy_kemasan_beli") if legacy_evidence else None,
        "legacy_purchase_conversion": legacy_evidence.get("legacy_isi_dasar") if legacy_evidence else None,
        "purchase_unit_candidate": (legacy_evidence.get("legacy_kemasan_beli") if legacy_evidence else None) or (name_evidence["unit"] if name_evidence and not name_evidence["ambiguous_structure"] else None),
        "purchase_conversion_candidate": (legacy_evidence.get("legacy_isi_dasar") if legacy_evidence else None) or (name_evidence["total_qty"] if name_evidence and not name_evidence["ambiguous_structure"] else None),
        "scm_transaction_evidence": txn_evidence.get("GUDANG_BESAR"),
        "cibadak_transaction_evidence": txn_evidence.get("CIBADAK"),
        "product_name_evidence": name_evidence,
        "price_ratio_evidence": price_evidence or mismatch_evidence,
        "legacy_evidence": legacy_evidence,
        "evidence_count": evidence_count,
        "confidence": confidence,
        "issue_code": ",".join(dict.fromkeys(issues)),
        "issue_detail": " ".join(issue_detail_parts),
        "review_status": review_status,
        "approved_base_unit": None, "approved_middle_unit": None, "approved_middle_conversion": None,
        "approved_purchase_unit": None, "approved_purchase_conversion": None,
        "approved": None,
        "correction_note": "; ".join(correction_notes) if correction_notes else None,
        "warehouses_present": list(names.keys()),
    })

print(f"\nBuilt {len(results)} candidate records.")

with open(f"{OUT_DIR}/unit_conversion_candidates_real.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2, default=str)
print(f"Wrote {OUT_DIR}/unit_conversion_candidates_real.json")

# ---------------------------------------------------------------------
# warehouse_unit_comparison.csv
#
# The "Satuan Dasar" (base unit) column is, by construction, the SAME
# shared master field seen from each warehouse's file — so base-unit
# values essentially never differ across warehouses for a single SKU
# (confirmed: 0 BASE_UNIT_REVIEW_REQUIRED rows in this dataset). The
# "Gudang Besar buys in a large unit, transit warehouses hold/move the
# base unit" pattern the user asked to surface therefore does NOT show
# up as a base-unit mismatch — it shows up at the PACKAGING/PURCHASE
# layer (legacy purchase unit+conversion, or the derived candidate),
# which is what this comparison actually reports per SKU present in
# 2+ warehouses.
# ---------------------------------------------------------------------
comparison_rows = []
for r in results:
    if len(r["warehouses_present"]) < 2:
        continue
    scm_unit = r["gudang_besar_unit"]
    transit_unit = r["cibadak_unit"] or r["karangtengah_unit"]
    legacy_conv = r["legacy_purchase_conversion"]
    derived_conv = r["purchase_conversion_candidate"]
    try:
        conv_value = float(legacy_conv) if legacy_conv not in (None, "") else (
            float(derived_conv) if derived_conv not in (None, "") else None
        )
    except (TypeError, ValueError):
        conv_value = None

    if scm_unit and transit_unit and scm_unit != transit_unit:
        pattern = "BASE_UNIT_MISMATCH"
    elif conv_value and conv_value > 1:
        pattern = "SCM_LARGE_UNIT_TO_TRANSIT_BASE_UNIT_CANDIDATE"
    elif conv_value == 1:
        pattern = "NO_PACKAGING_LAYER"
    else:
        pattern = "NO_PACKAGING_EVIDENCE"

    comparison_rows.append({
        "SKU": r["sku"], "Item Name": r["item_name"],
        "SCM Unit": scm_unit, "Transit Unit": transit_unit,
        "Legacy Conversion": legacy_conv,
        "Derived Conversion": derived_conv,
        "Pattern": pattern,
        "Evidence": r["issue_code"],
        "Status": r["review_status"],
    })
pd.DataFrame(comparison_rows).to_csv(f"{OUT_DIR}/warehouse_unit_comparison.csv", index=False)
print(f"Wrote {OUT_DIR}/warehouse_unit_comparison.csv ({len(comparison_rows)} rows)")
